name: Start Test workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::678790208956:instance-profile/cyrus_batch
        aws-region: us-west-2
    - name: Checkout Repo
      uses: actions/checkout@v3

  end:
    runs-on: ubuntu-latest
    steps:
      - name: end test
        run: echo "End Test"
        shell: bash