name: Start Test workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::678790208956:role/cyrus_batch
        aws-region: us-west-2
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install pytest
        pip install boto3

  end:
    runs-on: ubuntu-latest
    steps:
      - name: end test
        run: echo "End Test"
        shell: bash

